### PR TITLE
[renamed]: big PR with all the new features (CC param adjust, updated SysEx parsing, ProgramChange patch select, and small UI improvements)

### PR DESCRIPTION
**Pull request by beau-seidon**
Added a buffer to remember up to 8 held notes for each MIDI channel, Notes are remembered in the order they were pressed. When the last-pressed note is released, the next most recent held note is sounded again without having to re-press the key. When notes are released from middle of the buffer, the more recent notes are shifted down to fill gaps and make room for new notes.

The result is that you can play fast legato style monophonic licks now (if the Sustain parameter is not set to 0) by holding one key and spamming others above and below, and it will definitely impress all the ladies

The MAX_POLY limit can be increased in the code to remember more held notes, but most people don't play with all 10 fingers at once. Increasing the value adds more loops, so 8 seemed like a decent value to maximize performance.

I added a temporary band-aid to check for polyphonic mode, which simply reverts to previous behavior, because I found that notes were sticking when assigner_upper_mode was POLY. It's something I will look into resolving properly in the future.
EDIT: also SPLIT mode

I also fixed a booboo from my very first pull request, so note_on & vel=0 will now send a note_off to the sequencer as well, not just the assigner_note_off call.

### CODE REVIEW

**Comment by beau-seidon** [comment]
every day i screw up something new on github XD

**Comment by Jaffe-** [comment]
Looked over the new commits @beau-seidon , looks good to me! Looks like you're getting comfortable with this rather messy code base and the way things are structured. The fix for the crash when receiving sysex messages was a really good catch, and the fix is exactly right.

The DMC change  is missing a corresponding update to the documentation, which still states MIDI note 60 is the first sample.

The two first fixup commits can be squashed, and same with the two next ones which deal with the legato mode (since the last one just fixes an issue introduced in the one before). You can use the interactive rebase feature in git to do this and then force push to the branch on github.

**Comment by beau-seidon** [comment]
Thanks for the feedback! I'm very happy to be able to contribute. 

Also thanks for the interactive rebase tip. That would have saved me a ton of headache on one of my other projects a while back.

I squashed the tiny commits, and updated the manual.tex file but I didn't generate an updated .pdf file for it.
Didn't know how, but also didn't bother to look it up...

I included the compiled binaries for deltacompress and gensysex (with the message header fix), for Windows users not familiar with compiling software. Is that alright?

**Comment by beau-seidon** [comment]
definitely should have requested this merge from a branch other than my master. this PR now includes all changes including reformatted / modularized CC handling, program change handling, and sysex parsing overhaul. 

it also compiles using make + avr-gcc with no errors or warnings and everything still seems to work!

we are all still testing, which is arguably the most enjoyable part! 

more changes to come soon from the wishlist

**Comment by Jaffe-** [comment]
It is awesome seeing the development going on here @beau-seidon and @circuitcreature! I'm unfortunately not able to spend much time on this project, and I realize that I'm not really the best person to test and quality check all of these new features either because I don't really use the NESizer actively as a musical tool. For me it has been a fun hobby project, first and foremost as a challenge to improve my electronics and software skills back when I was studying, but now it is a project that several people are apparently using musically in their production setups, and that is just beyond anything I could imagine!

I realize that the project is now becoming more community driven, and I don't want to stand in the way of bug fixes and new features coming in, or people having to build from different forks etc. So if you want, I can give you (@beau-seidon and @circuitcreature) collaborator status in the project, so you are able to push and merge PRs, create new releases and so on! Let me know if you want that. You'll of course have the honor of merging this PR!

**Comment by circuitcreature** [comment]
I would be happy to take on as a collaborator and im sure @beau-seidon  would be as well.

**Comment by beau-seidon** [comment]
Absolutely! 

Obviously yours is still the final say on the master branch, we will respect any requirements you may have regarding project direction, coding style, etc. And I'll only do my wacky experiments on my own fork lol. 

It would be useful if you gave us some guidelines to follow for merging into the master branch. For example, you stated in the past that the code should be able to compile using make, with the makefile you have set up, and you'd prefer no 3rd party libraries, and the syntax should pretty much follow K&R standard.

Maybe put a checklist in a Discussion thread we can follow so when you log in and look at the repo, you don't regret giving us a spare set of keys. Something also about tests you might like us to do to make sure the bits you want to work a specific way, still do. We can carry out the tests (if any) before merging to master.

Twisted Electrons has something similar with their TherapSID and MegaFM repos: rules like "don't break backward compatibility with saved patches" and "must pass these unit tests: ...".

**Comment by Jaffe-** [comment]
@beau-seidon @circuitcreature: You should have gotten an invite now!

Good idea to have some ground rules, I'll make a list we can have. It's mostly going to be the things you mentioned, plus PRs being cleaned up ("fixup" commits squashed etc.) before merging. It should also be a goal to keep a clean separation of changes in commits, although that can often be hard to do in practice. But two separate features should at least be in different commits where possible.

When it comes to the UI, it can be things that need changing there, or things that are annoying when using it. I'm open to changing the UI behavior as well (things like button combinations etc.), as long as the documentation is updated at the same time. I don't know if any of you have been able to build the documentation? It is a rather dodgy LaTex file, but should compile with most normal LaTex distributions I think.

**Comment by beau-seidon** [comment]
WOO! Thank you @Jaffe-. I promise I won't break anything on your main fork.

**Comment by beau-seidon** [comment]
> Good idea to have some ground rules, I'll make a list we can have. It's mostly going to be the things you mentioned, plus PRs being cleaned up ("fixup" commits squashed etc.) before merging. It should also be a goal to keep a clean separation of changes in commits, although that can often be hard to do in practice. But two separate features should at least be in different commits where possible.

Ha I got excited any merged this PR about one minute before you posted this. But I did choose to squash all previous commits and removed the little "nuisance commit" labels like "fixed a typo" in the merge description. 

I very much agree about the commit-per-feature while squashing the piddly stuff. It keeps the history clean. 
I intend to do all of my work on my own fork obviously, and will probably have a bunch of little commits on there, but each time I finish a new permanent feature or properly fix a bug, I'll PR to the master here. 
I think what I'll do is put in a PR, and then wait for someone else to review it and then accept it. I don't intend to merge my own PR's to this fork, for quality control reasons.


> When it comes to the UI, it can be things that need changing there, or things that are annoying when using it. I'm open to changing the UI behavior as well (things like button combinations etc.), as long as the documentation is updated at the same time. I don't know if any of you have been able to build the documentation? It is a rather dodgy LaTex file, but should compile with most normal LaTex distributions I think.

@circuitcreature created a new pdf version of the manual with some recent changes, but I did find one typo that I made which got compiled into his pdf before I fixed the tex file. But I didn't recompile the pdf after I found it... The only way I know how to convert tex to pdf is use some online service, and I was hesitant to do so because I don't know what sort of stuff they embed in the file. I looked in to using an application called TexMaker, but I haven't tried it yet.

**Comment by circuitcreature** [comment]
@beau-seidon I can recompile the pdf. It's not too difficult to setup with VScode, LaTeX Workshop works nice and has some decent instructions to get everything installed.

**Pull request merged**
